### ISSUE TITLE
Update to Lato 2.015

### ISSUE THREAD

**Issue by astorije** [betsol/lato-font#2]
Lato 2.015 was released in August this year: http://www.latofonts.com/2015/08/06/lato-font-family-updated-version-2-015/

It would be terrific if this repository mirrored this too :-)

Thanks!

**Comment by Okipa** [comment]
+1 !

**Comment by slavafomin** [comment]
Hello! Thank you for letting me know. However, we are not using this font in our current projects right now and are not able to divert our resources into it at the moment. Please, feel free to create a PR replacing font files with more current ones. I will be happy to merge it!

Cheers!

**Comment by slavafomin** [comment]
Hey guys, I've asked @gaintsev to update the version of fonts in this repository, he will be able to do this when time permits.

**Comment by astorije** [comment]
Ping? :)

**Comment by slavafomin** [comment]
Just released version `2.0.0`, feel free to update your projects!
Thanks to @gaintsev!
