### ISSUE TITLE
Update font with woff2

### ISSUE THREAD

**Issue by tamascsaba** [betsol/lato-font#6]
The newest lato font contain woff2 files to
http://www.latofonts.com/download/Lato2OFLWeb.zip

**Comment by tamascsaba** [comment]
@slavafomin ??

**Comment by slavafomin** [comment]
Hello @tamascsaba!

I've added (@a7c8c0529) support for WOFF2 font type.

Could you please check it out from master and let me know if it works ok, so I can release it?

Thanks.

**Comment by tamascsaba** [comment]
Nice work :+1: thx
