### ISSUE TITLE
just use woff and woff2

### ISSUE THREAD

**Issue by DanielRuf** [betsol/lato-font#7]
We can remove the other font files

http://caniuse.com/?feat=#woff
http://caniuse.com/?feat=#woff2

Supported since IE9

**Comment by slavafomin** [comment]
Hello! Thank you for your interest in this module!

However, do you have more information and use cases to back it up?

**Comment by DanielRuf** [comment]
woff and woff2 are supported by all browsers and use better compression than the other filetypes.

http://stackoverflow.com/a/11002874/753676
http://davidensinger.com/2014/10/update-your-font-face-file-formats-to-just-use-woff-and-woff2/

The other file types are just needed for unsupported and outdated browsers which should not be and are not used anymore.

**Comment by slavafomin** [comment]
Thank you @DanielRuf for pointing this out. I've just released a new major version of the library to make this work. Please let me know if it works for you. Cheers!

@b25aa86

**Comment by DanielRuf** [comment]
Works perfect for me.
